name: Build

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/latex:2.9
        with:
          args: >- # allows you to break string into multiple lines
            --pdf-engine=xelatex
            --output output.pdf
            index.md
      - uses: actions/upload-artifact@master
        with:
          name: output.pdf
          path: output.pdf
